default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("PGHOST", "localhost") %>
  port: <%= ENV.fetch("PGPORT", 5432) %>
  username: <%= ENV.fetch("PGUSER", "postgres") %>
  password: <%= ENV.fetch("PGPASSWORD", "") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: banner_gallery_backend_development

test:
  <<: *default
  database: banner_gallery_backend_test

production:
  primary:
    adapter: postgresql
    encoding: unicode
    database: <%= ENV.fetch("DB_NAME", "banner_gallery_db") %>
    pool: 5
    username: <%= ENV.fetch("DB_USERNAME", "banner_admin") %>
    password: <%= ENV.fetch("DB_PASSWORD") %>
    host: <%= ENV.fetch("DB_HOST") %>

  queue:
    adapter: postgresql
    url: <%= ENV["DATABASE_URL"] %>
    pool: 5

  cable:
    adapter: postgresql
    encoding: unicode
    database: <%= ENV.fetch("DB_NAME", "banner_gallery_db") %>
    username: <%= ENV.fetch("DB_USERNAME", "banner_admin") %>
    password: <%= ENV.fetch("DB_PASSWORD") %>
    host: <%= ENV.fetch("DB_HOST") %>
    pool: 5

    cache:
    adapter: postgresql
    encoding: unicode
    database: <%= ENV.fetch("DB_NAME", "banner_gallery_db") %>
    username: <%= ENV.fetch("DB_USERNAME", "banner_admin") %>
    password: <%= ENV.fetch("DB_PASSWORD") %>
    host: <%= ENV.fetch("DB_HOST") %>
