default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("PGHOST", "localhost") %>
  port: <%= ENV.fetch("PGPORT", 5432) %>
  username: <%= ENV.fetch("PGUSER", "postgres") %>
  password: <%= ENV.fetch("PGPASSWORD", "") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: banner_gallery_backend_development

test:
  <<: *default
  database: banner_gallery_backend_test

production:
  primary:
    url: <%= ENV['DATABASE_URL'] %>
    pool: 5

  queue:
    url: <%= ENV['DATABASE_URL'] %>
    pool: 5

  cable:
    url: <%= ENV['DATABASE_URL'] %>
    pool: 5

  cache:
    url: <%= ENV['DATABASE_URL'] %>
    pool: 5
