name: Deploy to Render

on:
  push:
    branches:
      - main  # ← 本番ブランチ

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: HTTP request to Render deploy hook
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
